# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
if Vagrant.has_plugin? "vagrant-vbguest"
config.vbguest.no_install = true
config.vbguest.auto_update = false
config.vbguest.no_remote = true
end
config.vm.define :dnstest do |dnstest|
dnstest.vm.box = "bento/ubuntu-20.04"
dnstest.vm.network :private_network, ip: "192.168.20.2"
dnstest.vm.hostname = "dnstest"
end
  config.vm.provision :shell, privileged: false, run: "always", inline: %(
    cd /vagrant/
  )
end